=== FoXDev-404/WT_Lab_Manual/students.dtd
<!ELEMENT students (student+)>
<!ELEMENT student (name, rollno, course, email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT rollno (#PCDATA)>
<!ELEMENT course (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== FoXDev-404/WT_Lab_Manual/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!-- <?xml-stylesheet type="text/xsl" href="style.xsl"?> -->
<!DOCTYPE students SYSTEM "students.dtd">
<students>
    <student>
        <name>Rajpal Nishad</name>
        <rollno>101</rollno>
        <course>Computer Science</course>
        <email>rajpal@example.com</email>
    </student>
    <student>
        <name>Nikhil</name>
        <rollno>102</rollno>
        <course>Data Science</course>
        <email>Nikhil@example.com</email>
    </student>
</students>
